numero1  =  int ( input ( "Ingrese un número entero:" ))
numero2  =  int ( input ( "Ingrese otro número:" ))
numero3  =  int ( input ( "Ingrese otro número:" ))
numero4  =  int ( input ( "Ingrese otro número:" ))
numero5  =  int ( input ( "Ingrese otro número:" ))
numero6  =  int ( input ( "Ingrese otro número:" ))
numero7  =  int ( input ( "Ingrese otro número:" ))
numero8  =  int ( input ( "Ingrese otro número:" ))
numero9  =  int ( input ( "Ingrese otro número:" ))
numero10  =  int ( input ( "Ingrese otro número:" ))
print ( "La suma de los números ingresados ​​es:" , numero1  +  numero2  +  numero3  +  numero4  +  numero5  +  numero6  +  numero7  +  numero8  +  numero9  +  numero10 )
print ( "El promedio de los números ingresados ​​es:" , ( numero1  +  numero2  +  numero3  +  numero4  +  numero5  +  numero6  +  numero7  +  numero8  +  numero9  +  numero10 ) /  10 )